trigger:
  - main  # Runs pipeline on push to 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use a Linux-based agent

steps:
  - task: UseNode@1  # Install Node.js
    inputs:
      version: '18.x'

  - script: |
      npm install  
      npx playwright install --with-deps  
    displayName: 'Install Dependencies'

  - script: |
      npm test
    displayName: 'Run Playwright Tests'
